namespace Tahseen.Domain.Enums;

public enum Nationality : byte
{
    Uzbek = 0,
    American = 1,
    Argentine = 2,
    Australian = 3,
    Austrian = 4,
    Azerbaijani = 5,
    Brazilian = 6,
    British = 7,
    Canadian = 8,
    CentralAfrican = 9,
    Chinese = 10,
    Colombian = 11,
    Czech = 12,
    Danish = 13,
    Dutch = 14,
    Egyptian = 15,
    French = 16,
    German = 17,
    Greek = 18,
    Indian = 19,
    Indonesian = 20,
    Italian = 21,
    Japanese = 22,
    Kazakhstani = 23,
    KoreanSouth = 24,
    Kyrgyz = 25,
    Latvian = 26,
    Malaysian = 27,
    Mexican = 28,
    Pakistani = 29,
    Polish = 30,
    Portuguese = 31,
    Qatari = 32,
    Romanian = 33,
    Russian = 34,
    Saudi = 35,
    Slovenian = 36,
    Somali = 37,
    Spanish = 38,
    Tajik = 39,
    Turkish = 40,
    Vatican = 41,
    Other = 42
}

